title: onlyx.tech
description: Ramblings of Stephen English
theme: just-the-docs

url: https://onlyx.tech

search_enabled: false

plugins:
  - jekyll-feed
  - jekyll-redirect-from

feed:
  collections:
    posts:
      path: "/feed.xml"

aux_links:
  Contact Me: "mailto:steve@secomputing.co.uk"
